#pragma once
#include <string_view>
// Generated by export-container-helpers.mjs from the frozen Docker integration.
namespace devbox::container_helpers {
inline constexpr std::string_view list_python = R"CPP_PY(
import json
import os
import stat
import sys
import time

root = sys.argv[1]
recursive = sys.argv[2] == "1"
max_depth = max(1, int(sys.argv[3]))
max_entries = max(1, int(sys.argv[4]))
timeout_ms = max(1, int(sys.argv[5]))
excluded = {str(x).lower() for x in json.loads(sys.argv[6])}
deadline = time.monotonic() + timeout_ms / 1000.0
entries = []
pruned = 0
skipped = 0
timed_out = False
truncated = False
stack = [(root, 0)]

while stack:
    if time.monotonic() >= deadline:
        timed_out = True
        break
    current, depth = stack.pop()
    try:
        info = os.lstat(current)
    except (FileNotFoundError, PermissionError, NotADirectoryError):
        skipped += 1
        continue
    mode = info.st_mode
    kind = "l" if stat.S_ISLNK(mode) else "d" if stat.S_ISDIR(mode) else "f" if stat.S_ISREG(mode) else "?"
    if depth > 0 or not stat.S_ISDIR(mode) or recursive:
        entries.append(f"{kind}\t{current}")
        if len(entries) >= max_entries:
            truncated = True
            break
    if not recursive or not stat.S_ISDIR(mode) or depth >= max_depth:
        continue
    try:
        children = sorted(os.scandir(current), key=lambda e: (e.name.lower(), e.name), reverse=True)
    except (FileNotFoundError, PermissionError, NotADirectoryError):
        skipped += 1
        continue
    for child in children:
        if child.name.lower() in excluded:
            pruned += 1
            continue
        stack.append((child.path, depth + 1))

if entries:
    sys.stdout.write("\n".join(entries) + "\n")
notices = []
if timed_out:
    notices.append(f"listing stopped after {timeout_ms} ms")
if truncated:
    notices.append(f"listing capped at {max_entries} entries")
if pruned:
    notices.append(f"pruned {pruned} excluded directories")
if skipped:
    notices.append(f"skipped {skipped} inaccessible or vanished paths")
if notices:
    sys.stderr.write("; ".join(notices) + "\n")
)CPP_PY";
inline constexpr std::string_view read_text_python = R"CPP_PY(
import os
import stat
import sys

path = sys.argv[1]
max_bytes = max(1, int(sys.argv[2]))
info = os.stat(path)
if not stat.S_ISREG(info.st_mode):
    raise SystemExit("Not a regular file.")
with open(path, "rb") as handle:
    sys.stdout.buffer.write(handle.read(max_bytes))
)CPP_PY";
inline constexpr std::string_view write_text_python = R"CPP_PY(
import os
import sys

path = sys.argv[1]
append = sys.argv[2] == "1"
create_dirs = sys.argv[3] == "1"
parent = os.path.dirname(path)
if create_dirs and parent and parent != ".":
    os.makedirs(parent, exist_ok=True)
with open(path, "ab" if append else "wb") as handle:
    handle.write(sys.stdin.buffer.read())
)CPP_PY";
inline constexpr std::string_view large_read_python = R"CPP_PY(
import base64
import hashlib
import json
import os
import stat as statmod
import sys

file_path = sys.argv[1]
offset_requested = max(0, int(sys.argv[2]))
bytes_requested = max(1, int(sys.argv[3]))
file_stat = os.stat(file_path)
if not statmod.S_ISREG(file_stat.st_mode):
    raise SystemExit("Not a regular file.")
actual_offset = min(offset_requested, file_stat.st_size)
bytes_to_read = max(0, min(bytes_requested, file_stat.st_size - actual_offset))
with open(file_path, "rb") as handle:
    handle.seek(actual_offset)
    chunk = handle.read(bytes_to_read)
result = {
    "path": file_path,
    "file_size": file_stat.st_size,
    "offset_bytes_requested": offset_requested,
    "offset_bytes": actual_offset,
    "bytes_requested": bytes_requested,
    "bytes_returned": len(chunk),
    "next_offset_bytes": actual_offset + len(chunk),
    "eof": actual_offset + len(chunk) >= file_stat.st_size,
    "content_sha256": hashlib.sha256(chunk).hexdigest(),
    "content_base64": base64.b64encode(chunk).decode("ascii"),
}
sys.stdout.write(json.dumps(result))
)CPP_PY";
inline constexpr std::string_view large_write_python = R"CPP_PY(
import base64
import binascii
import hashlib
import json
import os
import re
import stat as statmod
import sys

def fail(message):
    raise SystemExit(message)

file_path = sys.argv[1]
append = sys.argv[2] == "1"
create_dirs = sys.argv[3] == "1"
expected_sha256 = sys.argv[4].strip().lower() if len(sys.argv) > 4 and sys.argv[4] else ""
stdin_base64 = sys.stdin.read()
normalized = "".join(stdin_base64.split())
if normalized:
    try:
        payload = base64.b64decode(normalized, validate=True)
    except binascii.Error:
        fail("Invalid base64 payload.")
    if base64.b64encode(payload).decode("ascii") != normalized:
        fail("Invalid base64 payload.")
else:
    payload = b""
content_sha256 = hashlib.sha256(payload).hexdigest()
if expected_sha256:
    if not re.fullmatch(r"[a-f0-9]{64}", expected_sha256):
        fail("expected_sha256 must be a 64-character SHA-256 hex string.")
    if expected_sha256 != content_sha256:
        fail("Decoded payload SHA-256 did not match expected_sha256.")
target_existed = False
previous_file_size = 0
try:
    initial_stat = os.stat(file_path)
    if not statmod.S_ISREG(initial_stat.st_mode):
        fail("Target exists but is not a regular file.")
    target_existed = True
    previous_file_size = initial_stat.st_size
except FileNotFoundError:
    pass
parent_dir = os.path.dirname(file_path)
if create_dirs and parent_dir and parent_dir != ".":
    os.makedirs(parent_dir, exist_ok=True)
with open(file_path, "ab" if append else "wb") as handle:
    handle.write(payload)
final_stat = os.stat(file_path)
if not statmod.S_ISREG(final_stat.st_mode):
    fail("Target is not a regular file after write.")
verified = False
verification_mode = ""
file_sha256 = None
if append:
    verification_mode = "suffix-bytes"
    if len(payload) == 0:
        verified = True
    else:
        with open(file_path, "rb") as handle:
            handle.seek(previous_file_size)
            verified = handle.read(len(payload)) == payload
else:
    verification_mode = "whole-file-sha256"
    digest = hashlib.sha256()
    with open(file_path, "rb") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                break
            digest.update(chunk)
    file_sha256 = digest.hexdigest()
    verified = final_stat.st_size == len(payload) and file_sha256 == content_sha256
if not verified:
    fail("Mirror verification failed after writing the payload.")
result = {
    "path": file_path,
    "append": bool(append),
    "previous_file_size": previous_file_size,
    "final_file_size": final_stat.st_size,
    "bytes_written": len(payload),
    "content_sha256": content_sha256,
    "verification_mode": verification_mode,
    "verified": verified,
    "expected_sha256_verified": True if expected_sha256 else None,
    "target_existed": target_existed,
    "file_sha256": file_sha256,
}
sys.stdout.write(json.dumps(result))
)CPP_PY";
} // namespace devbox::container_helpers
