if(NOT DEFINED SOURCE_ROOT OR NOT DEFINED OUTPUT_DIR)
  message(FATAL_ERROR "Source and output directories are required")
endif()
function(git_value variable)
  execute_process(COMMAND git -C "${SOURCE_ROOT}" ${ARGN} RESULT_VARIABLE status
                  OUTPUT_VARIABLE value ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT status EQUAL 0)
    set(value unknown)
  endif()
  set(${variable} "${value}" PARENT_SCOPE)
endfunction()
git_value(sha rev-parse HEAD)
git_value(ref rev-parse --abbrev-ref HEAD)
git_value(tree rev-parse "HEAD^{tree}")
git_value(status status --porcelain --untracked-files=all)
git_value(diff diff --binary HEAD)
git_value(untracked ls-files --others --exclude-standard)
set(dirty false)
if(NOT status STREQUAL "")
  set(dirty true)
endif()
if(status STREQUAL unknown)
  set(dirty unknown)
endif()
# Include dirty tracked content and untracked files in the build identity.
set(identity "${sha}\n${ref}\n${tree}\n${dirty}\n${diff}\n${COMPILER}\n${VERSION}")
string(REPLACE "\n" ";" untracked_files "${untracked}")
foreach(path IN LISTS untracked_files)
  if(EXISTS "${SOURCE_ROOT}/${path}" AND NOT IS_DIRECTORY "${SOURCE_ROOT}/${path}")
    file(SHA256 "${SOURCE_ROOT}/${path}" digest)
    string(APPEND identity "\n${path}:${digest}")
  endif()
endforeach()
string(SHA256 fingerprint "${identity}")
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(previous "")
if(EXISTS "${OUTPUT_DIR}/identity.sha256")
  file(READ "${OUTPUT_DIR}/identity.sha256" previous)
endif()
if(NOT previous STREQUAL fingerprint OR NOT EXISTS "${OUTPUT_DIR}/build_identity.hpp")
  string(TIMESTAMP built "%s" UTC)
  set(text "#pragma once\nnamespace devbox::build_identity {\n")
  foreach(field sha ref tree dirty fingerprint built)
    string(REPLACE "\\" "\\\\" escaped "${${field}}")
    string(REPLACE "\"" "\\\"" escaped "${escaped}")
    string(APPEND text "inline constexpr const char* ${field} = \"${escaped}\";\n")
  endforeach()
  string(APPEND text "inline constexpr const char* compiler = \"${COMPILER}\";\ninline constexpr const char* version = \"${VERSION}\";\n}\n")
  file(WRITE "${OUTPUT_DIR}/build_identity.hpp.tmp" "${text}")
  file(COPY_FILE "${OUTPUT_DIR}/build_identity.hpp.tmp" "${OUTPUT_DIR}/build_identity.hpp" ONLY_IF_DIFFERENT)
  file(WRITE "${OUTPUT_DIR}/identity.sha256" "${fingerprint}")
endif()
